# Generated by Django 6.0.4 on 2026-04-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sampletable',
            fields=[
                ('reg_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=19)),
                ('dob', models.DateField(null=True)),
                ('feedback', models.TextField(null=True)),
                ('submit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
