# Generated by Django 6.0.4 on 2026-04-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sampletable',
        ),
    ]
