# Generated by Django 6.0.4 on 2026-04-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripition',
            new_name='description',
        ),
    ]
