# Generated by Django 6.0.4 on 2026-04-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0005_rename_descripition_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social_science', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.FloatField()),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
