# Generated by Django 6.0.4 on 2026-04-20 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_ranksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_tasks', to='Students.student'),
        ),
    ]
